#include <conio.h>
#include "keyboard.h"
#include "addr.h"
#include "common.h"

/* {default, with_e0, with_shift, with_shift_e0} */
static unsigned char tbl[][4] = {
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_F9,KS_UNKNOWN,KS_F9,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_F5,KS_UNKNOWN,KS_F5,KS_UNKNOWN},
{KS_F3,KS_UNKNOWN,KS_F3,KS_UNKNOWN},
{KS_F1,KS_UNKNOWN,KS_F1,KS_UNKNOWN},
{KS_F2,KS_UNKNOWN,KS_F2,KS_UNKNOWN},
{KS_F12,KS_UNKNOWN,KS_F12,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_F10,KS_UNKNOWN,KS_F10,KS_UNKNOWN},
{KS_F8,KS_UNKNOWN,KS_F8,KS_UNKNOWN},
{KS_F6,KS_UNKNOWN,KS_F6,KS_UNKNOWN},
{KS_F4,KS_UNKNOWN,KS_F4,KS_UNKNOWN},
{KS_TAB,KS_UNKNOWN,KS_TAB,KS_UNKNOWN},
{'`',KS_UNKNOWN,'~',KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_LALT,KS_RALT,KS_LALT,KS_RALT},
{KS_LSHIFT,KS_UNKNOWN,KS_LSHIFT,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_LCTRL,KS_RCTRL,KS_LCTRL,KS_RCTRL},
{'q',KS_UNKNOWN,'Q',KS_UNKNOWN},
{'1',KS_UNKNOWN,'!',KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{'z',KS_UNKNOWN,'Z',KS_UNKNOWN},
{'s',KS_UNKNOWN,'S',KS_UNKNOWN},
{'a',KS_UNKNOWN,'A',KS_UNKNOWN},
{'w',KS_UNKNOWN,'W',KS_UNKNOWN},
{'2',KS_UNKNOWN,'@',KS_UNKNOWN},
{KS_UNKNOWN,KS_WIN,KS_UNKNOWN,KS_WIN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{'c',KS_UNKNOWN,'C',KS_UNKNOWN},
{'x',KS_UNKNOWN,'X',KS_UNKNOWN},
{'d',KS_UNKNOWN,'D',KS_UNKNOWN},
{'e',KS_UNKNOWN,'E',KS_UNKNOWN},
{'4',KS_UNKNOWN,'$',KS_UNKNOWN},
{'3',KS_UNKNOWN,'#',KS_UNKNOWN},
{KS_UNKNOWN,KS_WIN,KS_UNKNOWN,KS_WIN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{' ',KS_UNKNOWN,' ',KS_UNKNOWN},
{'v',KS_UNKNOWN,'V',KS_UNKNOWN},
{'f',KS_UNKNOWN,'F',KS_UNKNOWN},
{'t',KS_UNKNOWN,'T',KS_UNKNOWN},
{'r',KS_UNKNOWN,'R',KS_UNKNOWN},
{'5',KS_UNKNOWN,'%',KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{'n',KS_UNKNOWN,'N',KS_UNKNOWN},
{'b',KS_UNKNOWN,'B',KS_UNKNOWN},
{'h',KS_UNKNOWN,'H',KS_UNKNOWN},
{'g',KS_UNKNOWN,'G',KS_UNKNOWN},
{'y',KS_UNKNOWN,'Y',KS_UNKNOWN},
{'6',KS_UNKNOWN,'^',KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{'m',KS_UNKNOWN,'M',KS_UNKNOWN},
{'j',KS_UNKNOWN,'J',KS_UNKNOWN},
{'u',KS_UNKNOWN,'U',KS_UNKNOWN},
{'7',KS_UNKNOWN,'&',KS_UNKNOWN},
{'8',KS_UNKNOWN,'*',KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{',',KS_UNKNOWN,'<',KS_UNKNOWN},
{'k',KS_UNKNOWN,'K',KS_UNKNOWN},
{'i',KS_UNKNOWN,'I',KS_UNKNOWN},
{'o',KS_UNKNOWN,'O',KS_UNKNOWN},
{'0',KS_UNKNOWN,')',KS_UNKNOWN},
{'9',KS_UNKNOWN,'(',KS_UNKNOWN},
{KS_UNKNOWN,KS_HOME,KS_UNKNOWN,KS_HOME},
{KS_UNKNOWN,KS_UP,KS_UNKNOWN,KS_UP},
{'.',KS_PAGE_UP,'>',KS_PAGE_UP},
{'/',KS_UNKNOWN,'?',KS_UNKNOWN},
{'l',KS_LEFT,'L',KS_LEFT},
{';',KS_UNKNOWN,':',KS_UNKNOWN},
{'p',KS_RIGHT,'P',KS_RIGHT},
{'-',KS_UNKNOWN,'_',KS_UNKNOWN},
{KS_UNKNOWN,KS_END,KS_UNKNOWN,KS_END},
{KS_UNKNOWN,KS_DOWN,KS_UNKNOWN,KS_DOWN},
{KS_UNKNOWN,KS_PAGE_DOWN,KS_UNKNOWN,KS_PAGE_DOWN},
{'\'',KS_INSERT,'"',KS_INSERT},
{KS_UNKNOWN,KS_DELETE,KS_UNKNOWN,KS_DELETE},
{'[',KS_UNKNOWN,'{',KS_UNKNOWN},
{'=',KS_UNKNOWN,'+',KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_CAPSLOCK,KS_UNKNOWN,KS_CAPSLOCK,KS_UNKNOWN},
{KS_RSHIFT,KS_UNKNOWN,KS_RSHIFT,KS_UNKNOWN},
{KS_ENTER,KS_ENTER,KS_ENTER,KS_ENTER},
{']',KS_UNKNOWN,'}',KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{'\\',KS_UNKNOWN,'|',KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_BACKSPACE,KS_UNKNOWN,KS_BACKSPACE,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{'1',KS_UNKNOWN,'1',KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{'4',KS_UNKNOWN,'4',KS_UNKNOWN},
{'7',KS_UNKNOWN,'7',KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{'0',KS_UNKNOWN,'0',KS_UNKNOWN},
{'.',KS_UNKNOWN,'.',KS_UNKNOWN},
{'2',KS_UNKNOWN,'2',KS_UNKNOWN},
{'5',KS_UNKNOWN,'5',KS_UNKNOWN},
{'6',KS_UNKNOWN,'6',KS_UNKNOWN},
{'8',KS_UNKNOWN,'8',KS_UNKNOWN},
{KS_ESCAPE,KS_UNKNOWN,KS_ESCAPE,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_F11,KS_UNKNOWN,KS_F11,KS_UNKNOWN},
{'+',KS_UNKNOWN,'+',KS_UNKNOWN},
{'3',KS_UNKNOWN,'3',KS_UNKNOWN},
{'-',KS_UNKNOWN,'-',KS_UNKNOWN},
{'*',KS_UNKNOWN,'*',KS_UNKNOWN},
{'9',KS_UNKNOWN,'9',KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN,KS_UNKNOWN},
{KS_F7,KS_UNKNOWN,KS_F7,KS_UNKNOWN},
};

#define NSYM (sizeof(tbl)/sizeof(tbl[0]))

void
init_keyboard_driver(struct keyboard_driver *drv)
{
    drv->state = 0;
}

int
read_next_keyevent(struct keyevent *ev, struct keyboard_driver *drv)
{
    unsigned char st, c;
top:
    st = inp(PS2_STATE);

    if (st & 1) {
        /* empty */
        return 0;
    }

    c = inp(PS2_RX);

    if (c == 0xf0) {
        drv->state |= KBD_STATE_F0;
    } else if (c == 0xe0) {
        drv->state |= KBD_STATE_E0;
    } else {
        if (drv->state & KBD_STATE_F0) {
            ev->press = 0;
        } else {
            ev->press = 1;
        }

        if (c < NSYM) {
            if (drv->state & KBD_STATE_E0) {
                if (drv->state & KBD_STATE_EITHER_SHIFT) {
                    /* e0 + shift */
                    ev->keysym = tbl[c][4];
                } else {
                    /* e0 */
                    ev->keysym = tbl[c][1];
                }
            } else {
                if (drv->state & KBD_STATE_EITHER_SHIFT) {
                    /* e0 + shift */
                    ev->keysym = tbl[c][2];
                } else {
                    /* e0 */
                    ev->keysym = tbl[c][0];
                }
            }
        } else {
            ev->keysym = KS_UNKNOWN;
        }

        if (ev->press) {
            if (ev->keysym == KS_LSHIFT) {
                drv->state |= KBD_STATE_LSHIFT;
            } else if (ev->keysym == KS_RSHIFT) {
                drv->state |= KBD_STATE_RSHIFT;
            }
        } else {
            if (ev->keysym == KS_LSHIFT) {
                drv->state &= ~KBD_STATE_LSHIFT;
            } else if (ev->keysym == KS_RSHIFT) {
                drv->state &= ~KBD_STATE_RSHIFT;
            }
        }

        drv->state &= ~(KBD_STATE_F0 | KBD_STATE_E0);

        return 1;
    }

    goto top;
}
